/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Bit_Math.h"
#include "Std_Types.h"
#include "RCC_Interface.h"

RCC_config_t rcc = { .System_Clock = PLL_SYS_CLK, .PLL_Source = PLL_HSI_CLK ,
					 .PLLM = 4 , .PLLN = 50 , .PLLP = 4 ,
					 .AHB_Prescaler = RCC_AHB_PRESCALER_DIV_2,
					 .APB1_Prescaler = RCC_APB1_PRESCALER_DIV_16, .APB2_Prescaler = RCC_APB2_PRESCALER_DIV_16};
int main(void)
{
	Std_ReturnType RET = E_OK;
	RET = HAL_RCC_Clk_Config(&rcc);
	RET = HAL_RCC_Enable_Clk(OTGHSULPI_PERIPHERAL);
	RET = HAL_RCC_Enable_Clk(DCMI_PERIPHERAL);
	RET = HAL_RCC_Enable_Clk(QUADSPI_PERIPHERAL);
	RET = HAL_RCC_Enable_Clk(USART3_PERIPHERAL);
	RET = HAL_RCC_Enable_Clk(USART6_PERIPHERAL);
    return 0;
}
