/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Bit_Math.h"
#include "Std_Types.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "STK_Interface.h"

void STK_ISR (void);
RCC_config_t rcc = { .System_Clock = HSI_SYS_CLK, .AHB_Prescaler = RCC_AHB_PRESCALER_DIV_1,
					 .APB1_Prescaler = RCC_APB1_PRESCALER_DIV_1, .APB2_Prescaler = RCC_APB2_PRESCALER_DIV_1};

GPIO_config_t led = { .Port = GPIO_PORTA , .Pin = GPIO_PIN5 , .Pin_Direction = GPIO_OUTPUT , .Pin_connection = GPIO_PUSH_PULL,
					  .Pin_Speed = GPIO_OUTPUT_MEDIUM_SPEED , .Pin_Pull = GPIO_PULL_UP};

STK_config_t stk = {.stk_clk = STK_AHB_8_CLK , .stk_value = 1000000, .stk_InterruptHandler = STK_ISR};

int main(void)
{
	HAL_RCC_Clk_Config(&rcc);
	HAL_RCC_Enable_Clk(GPIOA_PERIPHERAL);
	HAL_GPIO_Init(&led);
	HAL_STK_Init(&stk);
	//HAL_STK_Set_Single_Shot(&stk);
	HAL_STK_Set_Multi_Shot(&stk);
    /* Loop forever */
	while (1){
		//Code to toggle led with time = stk_value(us)
		//HAL_GPIO_Toggle_Pin(& led);
		//HAL_STK_Set_Busy_Wait(&stk);
	}
	return 0;
}

void STK_ISR (void){
	//HAL_GPIO_Set_Pin_Value(&led, GPIO_HIGH);
	HAL_GPIO_Toggle_Pin(& led);
}
