/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Bit_Math.h"
#include "Std_Types.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"

RCC_config_t rcc = { .System_Clock = HSI_SYS_CLK, .AHB_Prescaler = RCC_AHB_PRESCALER_DIV_1,
					 .APB1_Prescaler = RCC_APB1_PRESCALER_DIV_1, .APB2_Prescaler = RCC_APB2_PRESCALER_DIV_1};

GPIO_config_t led = { .Port = GPIO_PORTA , .Pin = GPIO_PIN5 , .Pin_Direction = GPIO_OUTPUT , .Pin_connection = GPIO_PUSH_PULL,
					  .Pin_Speed = GPIO_OUTPUT_MEDIUM_SPEED};
int main(void)
{
	Std_ReturnType RET = E_OK;
	RET = HAL_RCC_Clk_Config(&rcc);
	RET = HAL_RCC_Enable_Clk(GPIOA_PERIPHERAL);
	RET = HAL_GPIO_Init(&led);
	while (1){
		/*Turn on led*/
		RET = HAL_GPIO_Toggle_Pin(&led);
		for ( uint32 i = 0 ; i< 500000 ; i++){
			__asm("NOP");
		}
	}

    return 0;
}
